version: '3.8'

services:
  multiverse-peer:
    image: multiverse-vcs/multiverse-peer:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./fleeta-vehicles-data:/fleeta-vehicles-data
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    environment:
      - GO111MODULE=on
    privileged: true
    entrypoint: ["/entrypoint.sh"]
