version: '3.8'

services:
  multiverse-peer1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./peer1-data:/fleeta-vehicles-data
      - ./shared-data:/shared-data  
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    environment:
      - GO111MODULE=on
    privileged: true


  multiverse-peer2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./peer2-data:/fleeta-vehicles-data
      - ./shared-data:/shared-data 
    ports:
      - "4002:4001"
      - "5002:5001"
      - "8081:8080"
    environment:
      - GO111MODULE=on
    privileged: true

volumes:
  shared-data:
