
version: "3.7"
services:
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./orchestrator/mqtt-broker/config:/mosquitto/config:rw
      - ./orchestrator/mqtt-broker/data:/mosquitto/data:rw
      - ./orchestrator/mqtt-broker/log:/mosquitto/log:rw
    restart: unless-stopped

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:

networks:
  default:
    name: mqtt5-network

